### PR TITLE
Narine/rule integration split eval from approach

### PR DESCRIPTION
**Pull request by NarineK**
+ regenerated the chats for probability distribution
+ added a figure for overlap/conflict/coverage
+ added/modified some descriptions

### CODE REVIEW

**Comment by NarineK** [comment]
@mktal

**Comment by mktal** [comment]
@NarineK Thanks. One question: why do we need train/test split in this case? Since the input to the generative model is only label function and unlabeled data right?

**Comment by mktal** [comment]
Also, how do you compute conflict, coverage and overlap? Especially, overlap with what? Maybe you described in the text and I missed

**Comment by NarineK** [comment]
Regarding train/test split: I fit generative model only with unlabeled train data but then after the model is fitted, I compute the marginal probs on test data using that model and based on those probs predict the labels and compare with ground truth.

**Comment by NarineK** [comment]
For computing the coverage, conflicts and overlaps: it computes the overlaps of functions with each other: I use snorkel to compute:
https://github.com/HazyResearch/snorkel/blob/master/snorkel/utils.py#L79

**Comment by NarineK** [comment]
This pull request has some issues. Created another one: #2 . Please look at that one ...

**Pull request closed without merging**
